#This file stores configuration options for AngelicaShaders, such as the currently active shaderpack
#Fri May 29 08:55:23 BRT 2026
enableDebugOptions=false
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v8.2.09.zip
